import { AuthService } from "./auth/service";
import { AuthRepository } from "./auth/repository";
import { ClassroomService } from "./classroom/service";
import { ClassroomRepository } from "./classroom/repository";
import { AssignmentService } from "./assignment/service";
import { AssignmentRepository } from "./assignment/repository";
import { GroupService } from "./group/service";
import { GroupRepository } from "./group/repository";
import { ClassroomMemberService } from "./classroommember/service";
import { ClassroomMemberRepository } from "./classroommember/repository";
import { UserService } from "./user/service";
import { UserRepository } from "./user/repository";
import { ProjectService } from "./project/service";
import { ProjectRepository } from "./project/repository";
import { DiscordService } from "./discord/service";
import { DiscordRepository } from "./discord/repository";

const authRepository = new AuthRepository();
export const authService = new AuthService(authRepository);
const classroomRepository = new ClassroomRepository();
export const classroomService = new ClassroomService(classroomRepository);
const assignmentRepository = new AssignmentRepository();
export const assignmentService = new AssignmentService(assignmentRepository);
const groupRepository = new GroupRepository();
export const groupService = new GroupService(groupRepository);
const classroomMemberRepository = new ClassroomMemberRepository();
export const classroomMemberService = new ClassroomMemberService(classroomMemberRepository);
const userRepository = new UserRepository();
export const userService = new UserService(userRepository);
const projectRepository = new ProjectRepository();
export const projectService = new ProjectService(projectRepository);
const discordRepository = new DiscordRepository();
export const discordService = new DiscordService(discordRepository);
